---
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscredskey.yml
  tasks:
  - name: create  a new key pair - mykeypairtest
    ec2_ami:
      aws_access_key: "{{ aws_id }}"  
      aws_secret_key: "{{ aws_key }}"
      region: ap-south-1
      instance_id: i-0aa637ed73a9c43b2
      wait: no
      name: mynewami1
      tags:   
        Name: mynewami1
        Service: TestAmiservice1
    register: instance  

