---
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/awscredskey.yml
  tasks:
  - name: labling an existing volume
    ec2_vol:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: ap-south-1
      resource: vol-02c588d1ea2599342
      state: present
      tags: 
        Name: data_volume
    register: voltags    
      
    
 
 
