---
- hosts: all
  become: yes
  tasks:
  - name: Installing tomcat 
    yum:
      name: tomcat
      update_cache: yes
      state: present
  - name: restart tomcat
    service:
      name: tomcat
      state: restarted

